### PR TITLE
Phillmont Muktar : Assertions, Exception Handling, Throwing Exceptions, and Misc

### PR DESCRIPTION
**Pull request by pchunky**
Added chapters on Assertions, Exception Handling, and Throwing Exceptions. Also added a new section, "Supplemental Readings" for miscellaneous contents from everyone. I added an "Accessing files in WSL" chapter, since there were a lot of confusion in Piazza before.

Moved Type Erasure entry in textbook.md from Lecture 5 to Lecture 6, since it was introduced in Week 6. Also added entries for some textbook contributions which was not already in textbook.md.

### CODE REVIEW

**Comment by seanlowjk** [comment]
Thank you for your contribution! 

That's a super big PR XD 

Give us some time to take a look at it and we'll update you here if there are any updates! :D 

All the best for midterms!

**Comment by pchunky** [comment]
AHAHA Apologies if it was too many (*/ω＼*)
Thanks for updating me! Please kindly let me know if there is any changes I would have to made :D

**Comment by jamesleeht** [comment]
Thanks, it seems like you've already added the links to all the relevant contributions you made, this makes for an easier merge process on our end.

Btw, according to the merge conflict it seems like the Raw Types guide is now gone from the textbook?

**Comment by jamesleeht** [comment]
Looks good, thanks for the lecture 6 fix!

**Comment by pchunky** [comment]
Thanks for reviewing and approving too! Have a great weekend :)

**Pull request merged**
