### PR TITLE
Added note on variable capture by Jason Tay

### PR DESCRIPTION
**Pull request by jay9645**

### CODE REVIEW

**Comment by jamesleeht** [comment]
Hi, please make sure your file ends with the `.md` extension.

**Comment by seanlowjk** [comment]
Thanks Jay! Please also put in your full name at the name of the pull request so we can credit you for this submission! 

have a Nice Day!

**Comment by seanlowjk** [comment]
Do let us know in the comments when you are ready for your PR to be merged thanks Jason!

**Comment by jay9645** [comment]
Hi Sean, I added another note on streams and laziness, i think it should be ready to be merged, thanks!

**Pull request merged**
