### PR TITLE
Zhou Zijian: update textbook lecture05

### PR DESCRIPTION
**Pull request by BobbyZhouZijian**
Create a chapter on generic types and parameterised types.

### CODE REVIEW

**Comment by seanlowjk** [comment]
Hi ZiJian!

Thank you for your input! 

It seems that you have extracted a component from Piazza! May we understand what's the purpose of this chapter for before we proceed? 

Thanks!

**Comment by BobbyZhouZijian** [comment]
It focuses on clarifying the concepts of generic types and parameterised types. I find it quite important and prof also marked the original question as a good question. So I think it may be good to put it as a chapter.

**Comment by seanlowjk** [comment]
Ok cool! 

Maybe you can help by giving more context to the answer by quoting the question as well, and maybe explaining a bit more on generic and parameterised types

then we'll approve your PR! Thanks!

**Comment by BobbyZhouZijian** [comment]
Sure I will try to make the chapter more elaborate

**Comment by BobbyZhouZijian** [comment]
Have made changes to the file!

**Comment by seanlowjk** [comment]
Ok Thank you!

**Pull request merged**
