### PR TITLE
Leng Qian Yi: Override toString and equals method

### PR DESCRIPTION
**Pull request by lngqy**
description of Override toString and equals method and String.format uses for Lecture 2

### CODE REVIEW

**Comment by seanlowjk** [comment]
Thank you for your contribution! 

However, when you have the time, please do ensure that it is of `.md` format and any spaces should be replaced by **underscores**! 

Thank you and all the best for midterms!

**Comment by lngqy** [comment]
hi, sorry how do I change to .md ? do I just change the name of the file? and which spaces are you referring to?

**Comment by jamesleeht** [comment]
Yes change the name of the file. Additionally, your file should be within contents > textbook, not the root folder.

**Comment by lngqy** [comment]
sorry, how do I shift it over to the textbook? I am not familiar with GitHub and I am confused with the merging

**Comment by jamesleeht** [comment]
https://github.blog/2013-03-15-moving-and-renaming-files-on-github/

**Comment by lngqy** [comment]
I have made the changes, is it okay now?

**Comment by seanlowjk** [comment]
It's better! However, would it be better if you would be able to put it in the subdirectory instead? 

Thanks! 

image


`contents/textbook/lecture02/overrideToString/Override_toString_and_equals_method.md `

**Comment by seanlowjk** [comment]
Thank you for your contribution! 💯

**Pull request merged**
